spring:
  datasource:
    url: {{ .Values.db.url }}/auditdb
    username: '{{ .Values.db.username }}'
    password: '{{ .Values.db.password }}'
logging:
  level:
    com.opsmx.auditclientservice: INFO
standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv
oes:
  admin:
    user: admin
feign:
  client:
    config:
    platformservice:
      name: platformservice
      url: http://oes-platform:8095
    visibilityservice:
      name: visibilityservice
      url: http://oes-visibility:8096
