spring:
  datasource:
    url: {{ .Values.db.url }}/auditdb
    username: '{{ .Values.db.username }}'
    password: '{{ .Values.db.password }}'
logging:
  level:
    com.opsmx.auditclientservice: INFO
standardErrorCodes:
  filePath: /opsmx/conf/standard-error-code.csv
oes:
  admin:
    user: admin
feign:
  client:
    platformservice:
      name: platformservice
      url: http://oes-platform:8095
    visibilityservice:
      name: visibilityservice
      url: http://oes-visibility:8096
app:
  insights:
    adminuser: {{ .Values.saporgate.config.config.username }} # mandatory to provide admin user name to run admin jobs that compute insights counts

fixedDelay:
  in:
    milliseconds: 120000
initialDelay:
  in:
    milliseconds: 300000
