spring:
  datasource:
{{- if (eq .Values.secretStore "db") }}
    url: {{ .Values.db.url }}/oesdb
    username: {{ .Values.db.username }}
    password: {{ .Values.db.password }}
{{- end }}

secretManagement:
  source:
    config: {{ .Values.secretStore }}
  encryption: true
oes:
  rbac:
    enabled: true
  admin:
    user: admin
  platform:
    url: http://oes-platform:8095
  visibility:
    url: http://oes-visibility:8096
  dashboard:
    url: http://oes-dashboard:8094
pipeline-promotion:
  github:
    enabled: true
    username:  {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.username }}
    token: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.token }}
    branch: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.branch }}
    cloneUrl: https://{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.username }}:{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.token }}@{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.baseUrl }}/{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.organization }}/{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.repository }}
  bitbucket:
    enabled: false
    username:  {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.username }}
    token: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.token }}
    branch: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.branch }}
    cloneUrl: https://{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.username }}:{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.token }}@{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.baseUrl }}/{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.organization }}/{{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.repository }}
  amazonS3:
    enabled: false
    accessKeyId: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.AWS_ACCESS_KEY_ID }}
    secretAccessKey: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.AWS_SECRET_ACCESS_KEY }}
    region: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.awsregion }}
    bucketName: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.repository }} 
spinnaker:
  restart:
    endPoint: /webhooks/webhook/restartSpinnaker
  encrypt:
    key: {{ .Values.sapor.config.encrypt.key }}
datasources:
  platform: {{ .Values.sapor.config.datasources.platform }}
  
## Set the below field to true if agent for kubernetes
kubernetes:
  agent:
    enabled: {{ .Values.forwarder.enabled }}
    serverInternalHostName: opsmx-controller-controller1
    serverPort: 9003
    caCertfile: /opt/opsmx/controller/ca.crt
    certFile: /opt/opsmx/controller/cert/tls.crt
    keyFile: /opt/opsmx/controller/cert/tls.key
    image: {{ .Values.forwarder.agent.image }}
  template:
    path: /opt/opsmx/controller
    kubectlTemplateFileName: kubeconfig.template
    manifestTemplateFileName: deploy-agent.template
