oes:
  rbac:
    enabled: true
  admin:
    user: admin
spinnaker:
  restart:
    endPoint: /webhooks/webhook/restartSpinnaker
spring:
  datasource:
    url: {{ .Values.db.url }}/oesdb
    username: {{ .Values.db.username }}
    password: {{ .Values.db.password }}
datasources:
  platform: {{ .Values.sapor.config.datasources.platform }}
  
## Set the below field to true if agent for kubernetes
kubernetes:
  agent:
    enabled: {{ .Values.forwarder.enabled }}
    serverInternalHostName: opsmx-controller-controller1
    serverPort: 9003
    caCertfile: /opt/opsmx/controller/ca.crt
    certFile: /opt/opsmx/controller/cert/tls.crt
    keyFile: /opt/opsmx/controller/cert/tls.key
    image: {{ .Values.forwarder.agent.image }}
  template:
    path: /opt/opsmx/controller
    kubectlTemplateFileName: kubeconfig.template
    manifestTemplateFileName: deploy-agent.template
