apiVersion: v1
data:
  k8config-sync.sh: |+
    #!/bin/bash
    rm -rf spinnaker-poc
    mkdir -p /opsmx
    echo " ####### Cloning the Dynamic Account Repo #################"
    git clone  -c http.sslVerify=false https://USER:TOKEN@github.pie.apple.com/SpinCloud-GCP/spinnaker-poc.git
    cd spinnaker-poc/
    cat clouddriver-local.yml |grep -i opsmx|cut -f3 -d"/"  > /opsmx/config_files.txt
    for config in $(cat /opsmx/config_files.txt)
    do
    kubectl get secrets $config -o=jsonpath='{.data.*}'|base64 -d > /opsmx/$config
    done
kind: ConfigMap
metadata:
  name: k8config-sync
