apiVersion: v1
data:
  k8config-sync.sh: |+
    #!/bin/bash
    rm -rf $DYNAMIC_ACCOUNTS_REPO
    mkdir -p /opsmx
    echo " ####### Cloning the Dynamic Account Repo #################"
    git clone -c http.sslVerify=false $GIT_CLONE_PARAM
    cd $DYNAMIC_ACCOUNTS_REPO
    cat clouddriver-local.yml |grep -i opsmx|cut -f3 -d"/"  > /opsmx/config_files.txt
    for config in $(cat /opsmx/config_files.txt)
    do
    kubectl get secrets $config -o=jsonpath='{.data.*}'|base64 -d > /opsmx/$config
    done
kind: ConfigMap
metadata:
  name: k8config-sync
