{{- if (eq .Values.secretStore "vault")  }}
apiVersion: v1
data:
  vaultaddr: {{ .Values.vault.address }}
  vaulttoken: {{ .Values.vault.token }}
kind: Secret
metadata:
  name: vaultsec
type: Opaque
{{- end -}}
