{{- if (eq .Values.secretStore "vault")  }}
apiVersion: v1
data:
  vaultaddr: {{ .Values.secretStore.vaultaddress }}
  vaulttoken: {{ .Values.secretStore.vaulttoken }}
kind: Secret
metadata:
  name: vaultsec
type: Opaque
{{- end -}}
