apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "spinnaker.fullname" . }}-additional-profile-config-maps
  labels:
{{ include "spinnaker.standard-labels" . | indent 4 }}
{{/*
Render profiles for each service by merging predefined defaults with values passed by
.Values.halyard.additionalProfileConfigMaps.data
*/}}
{{- $profiles := dict "gate-local.yml" dict -}}

{{- /* Defaults: Disable S3 versioning on Front50 if Minio storage is used */}}
{{- /* https://www.spinnaker.io/setup/install/storage/minio/#editing-your-storage-settings */}}
{{- if .Values.minio.enabled -}}
{{- $_ := set $profiles "front50-local.yml" (dict "spinnaker" (dict "s3" (dict "versioning" false))) -}}
{{- end -}}

{{- /* Defaults: Add special settings for gate if GCE or ALB ingress is used */}}
{{- /* https://github.com/spinnaker/spinnaker/issues/1630#issuecomment-467359999 */}}
{{- if index $.Values.ingress "annotations" -}}
{{- if eq (index $.Values.ingress.annotations "kubernetes.io/ingress.class" | default "") "gce" "alb" "nsx" }}
{{- $tomcatProxySettings := dict -}}
{{- $_ := set $tomcatProxySettings "protocolHeader" "X-Forwarded-Proto" -}}
{{- $_ := set $tomcatProxySettings "remoteIpHeader" "X-Forwarded-For" -}}
{{- $_ := set $tomcatProxySettings "internalProxies" ".*" -}}
{{- $_ := set $tomcatProxySettings "httpsServerPort" "X-Forwarded-Port" -}}
{{- $_ := set $profiles "gate-local.yml" (dict "server" (dict "tomcat" $tomcatProxySettings)) -}}
{{- end -}}
{{- end -}}

{{- /* Merge dictionaries with passed values */}}
{{- $customProfilesEnabled := .Values.halyard.additionalProfileConfigMaps.create | default true -}}
{{- if and $customProfilesEnabled .Values.halyard.additionalProfileConfigMaps.data -}}
{{- $_ := mergeOverwrite $profiles .Values.halyard.additionalProfileConfigMaps.data -}}
{{- end -}}

{{- /* Convert the content of profiles to string unless it's already a string */}}
{{- range $filename, $content := $profiles -}}
{{- if not (typeIs "string" $content) -}}
{{- $_ := set $profiles $filename ($content | toYaml) -}}
{{- end -}}
{{- end -}}

{{- /* Pass content of profiles through tpl */}}
{{- range $filename, $content := $profiles -}}
{{- $_ := set $profiles $filename (tpl $content $) -}}
{{- end -}}

data:
{{ $profiles | toYaml | indent 2 }}
{{- if .Values.gitopsHalyard.pipelinePromotion.enabled }}
  # Custom stage for pipeline promotion;
  # same configuration can be put in a repo for gitops style
  orca-local.yml: |-
    job:
      preconfigured:
        kubernetes:
          - label: pipelineSyncToGit
            cloudProvider: kubernetes
            credentials: default
            description: Update git with pipelines in Spinnaker
            account: default
            application: gitopsHalyard.pipelinePromotion
            type: pipelineSyncToGit
            waitForCompletion: true
            parameters:
              - defaultValue: "app1,app2,..."
                description: "Please enter spinnaker applications separated by comma"
                label: spinnaker applications
                mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
                name: spinnaker_applications
              - defaultValue: "pipeline1,pipeline2..."
                description: "Please enter spinnaker pipelines separated by comma"
                label: pipieline names
                mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
                name: spinnaker_pipelines
            manifest:
                apiVersion: batch/v1
                kind: Job
                metadata:
                  generateName: pipepromot-
                  namespace: default
                spec:
                  backoffLimit: 0
                  template:
                    spec:
                      containers:
                      - command: ["bash", "scripts/deployer.sh"]
                        image: 'opsmxdev/pipepromot:1.0'
                        imagePullPolicy: Always
                        name: pipepromot
                        volumeMounts:
                        - mountPath: /home/opsmx/scripts
                          name: pipe-promot-scripts
                        - mountPath: /home/opsmx/.spin
                          name: spin-cli-config
                        env:
                          - name: spinnaker_applications
                            value: 'will be replaced'
                          - name: spinnaker_pipelines
                            value: 'will be replaced'
                          - name: command
                            value: 'upload'
                          - name: git_friendly_username
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_friendly_username
                          - name: git_friendly_username
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_friendly_username
                          - name: git_project
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_project
                          - name: git_refresh_enabled
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_refresh_enabled
                          - name: git_repo
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_repo
                          - name: git_user_email
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_user_email
                          - name: ignore_spin_errors
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: ignore_spin_errors
                          - name: git_secret_token
                            valueFrom:
                              secretKeyRef:
                                name: git-token
                                key: git_secret_token
                          - name: debug
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: debug
                          - name: pipelineconfig
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: pipelineconfig
                          - name: pipelineconfigdir
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: pipelineconfigdir
                          - name: pipelinecreateconf
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: pipelinecreateconf
                      volumes:
                      - configMap:
                          defaultMode: 420
                          name: pipe-promot-scripts
                        name: pipe-promot-scripts
                      - name: spin-cli-config
                        secret:
                          defaultMode: 420
                          secretName: spin-cli-config
                      restartPolicy: Never
                      serviceAccountName: default
          - label: pipelineSyncToSpinnaker
            cloudProvider: kubernetes
            credentials: default
            description: Sync Spinnaker pipelines from git
            account: default
            application: gitopsHalyard.pipelinePromotion
            type: pipelineSyncToSpinnaker
            waitForCompletion: true
            parameters:
              - defaultValue: "app1,app2,..."
                description: "Please enter spinnaker applications separated by comma"
                label: spinnaker applications
                mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
                name: spinnaker_applications
              - defaultValue: "pipeline1,pipeline2..."
                description: "Please enter spinnaker pipelines separated by comma"
                label: pipieline names
                mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
                name: spinnaker_pipelines
            manifest:
                apiVersion: batch/v1
                kind: Job
                metadata:
                  generateName: pipepromot-
                  namespace: default
                spec:
                  backoffLimit: 0
                  template:
                    spec:
                      containers:
                      - command: ["bash", "scripts/deployer.sh"]
                        image: 'opsmxdev/pipepromot:1.0'
                        imagePullPolicy: Always
                        name: pipepromot
                        volumeMounts:
                        - mountPath: /home/opsmx/scripts
                          name: pipe-promot-scripts
                        - mountPath: /home/opsmx/.spin
                          name: spin-cli-config
                        env:
                          - name: spinnaker_applications
                            value: 'will be replaced'
                          - name: spinnaker_pipelines
                            value: 'will be replaced'
                          - name: command
                            value: 'download'
                          - name: git_friendly_username
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_friendly_username
                          - name: git_friendly_username
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_friendly_username
                          - name: git_project
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_project
                          - name: git_refresh_enabled
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_refresh_enabled
                          - name: git_repo
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_repo
                          - name: git_user_email
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: git_user_email
                          - name: ignore_spin_errors
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: ignore_spin_errors
                          - name: git_secret_token
                            valueFrom:
                              secretKeyRef:
                                name: git-token
                                key: git_secret_token
                          - name: debug
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: debug
                          - name: pipelineconfig
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: pipelineconfig
                          - name: pipelineconfigdir
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: pipelineconfigdir
                          - name: pipelinecreateconf
                            valueFrom:
                              configMapKeyRef:
                                name: pipe-promot-config
                                key: pipelinecreateconf
                      volumes:
                      - configMap:
                          defaultMode: 420
                          name: pipe-promot-scripts
                        name: pipe-promot-scripts
                      - name: spin-cli-config
                        secret:
                          defaultMode: 420
                          secretName: local-spin-cli-config
                      restartPolicy: Never
                      serviceAccountName: default
{{- end }}
