#spring:
#  datasource:
#    url={{ .Values.db.url }}/visibilitydb
#    username={{ .Values.db.username }}
#    password={{ .Values.db.password }}

datasource.url: {{ .Values.db.url }}/visibilitydb
postgres.password: {{ .Values.db.password }}
postgres.username: {{ .Values.db.username }}

autopilot.api.url: http://oes-autopilot:8090
platform.service.url: http://oes-platform:8095

visiblity:
   connectors:
      configured: {{ .Values.visibility.config.configuredConnectors }}

logging:
  level:
    io:
      swagger:
        models:
          parameters:
            AbstractSerializableParameter: {{ .Values.visibility.config.logLevel }}
            
gate:
{{- if .Values.oesGate.port }}
  url: {{ .Values.oesGate.protocol }}://{{ .Values.oesGate.host }}:{{ .Values.oesGate.port }}
{{- else }}
  url: {{ .Values.oesGate.protocol }}://{{ .Values.oesGate.host }}
{{- end }}
