dependencies:
  - name: openldap
    version: ~1.2.1
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: installOpenLdap
  - name: spinnaker
    version: ~1.20.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: installSpinnaker
  - name: elasticsearch
    version: ^1.22.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: enableCentralLogging
  - name: elasticsearch-curator
    version: ^2.1.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: enableCentralLogging
  - name: kibana
    version: ^3.0.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: enableCentralLogging
  - name: fluent-bit
    version: ^1.9.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: enableCentralLogging
