dependencies:
  - name: openldap
    version: 1.2.3
    condition: installOpenLdap
  - name: spinnaker
    version: 2.2.1
    condition: installSpinnaker
  - name: redis
    version: 10.5.3
    condition: installRedis
  - name: elasticsearch
    version: 7.5.0
    condition: enableCentralLogging
  - name: kibana
    version: 7.5.0
    condition: enableCentralLogging
  - name: fluent-bit
    version: 2.8.2
    condition: enableCentralLogging
  - name: prometheus
    version: 11.16.2
    condition: spinnaker.enableCentralMonitoring
