job:
  preconfigured:
    kubernetes:
      - label: Custom Policy Stage
        type: custom Policy Stage
        description: Stage to do opa policy
        cloudProvider: kubernetes
        account: default
        waitForCompletion: true
        application: spin
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            labels:
              spinnakerlabel: deljob
            name: opastage
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                restartPolicy: Never
                containers:
                  - name: custom-opa-stage
                    args:
                      - |-
                        param=$(echo $time | sed 's/[][]//g') > /dev/null 2>&1
                        apk add jq > /dev/null 2>&1
                        cat >> opa.json <<EOL
                        {
                         "startTime": $param,
                         "application": "$application",
                         "name": "$name",
                         "trigger": {
                           "user": "$user"
                         }
                        }
                        EOL
                        cat opa.json
                        cat >> run.sh <<EOL
                        #/bin/sh
                        curl -sovX POST http://oes-sapor.oes:8085/v1/data/opa/pipelines/datetimeslot -d @opa.json --header "Content-Type: application/json" --insecure > out.txt
                        if [ $? -ne 0 ]
                        then
                        echo "========= EXECUTION FAILED ========"
                        else
                        cat out.txt | jq '.deny'
                        if [ $? -ne 0 ]
                        then
                        echo "=========== POLICY SUCCEDED! ============="
                        cat out.txt | jq '.'
                        exit 0
                        else
                        echo "==========  POLICY FAILED ========"
                        cat out.txt | jq '.'
                        exit 1
                        fi
                        fi
                        EOL
                        chmod +x run.sh > /dev/null 2>&1
                        sh run.sh
                    command:
                      - /bin/sh
                      - '-x'
                      - '-c'
                    env:
                      - name: application
                        value: "${execution.application}"
                      - name: name
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                      - name: user
                        value: "${execution.authentication.user}"
                    image: 'opsmxdev/apline-with-curl'
                    imagePullPolicy: Always
      - label: VerificationGate
        cloudProvider: kubernetes
        application: spin
        description: Stage for Verification Gate
        propertyFile: verificationgate
        account: default
        type: Verification
        waitForCompletion: true
        parameters:
          - defaultValue: ""
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: "0.1" 
            description: Please enter the Life Time in Hours like 0.5
            label: LifeTimeHours
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: lifetime
          - defaultValue: "70" 
            description: Please enter the Minimum Canary Result
            label: Minimum CanaryResult
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: minicanaryresult
          - defaultValue: "90" 
            description: Please enter the Canry Result Score
            label: CanaryResult Score
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: canaryresultscore
          - defaultValue: "true" 
            description: Please Enable Log with true / false
            label: Log Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: log
          - defaultValue: "true"
            description: Please Enable Metric with true / false
            label: Metric Analysis
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: metric
          - defaultValue: ""
            description: Please enter Baseline Start Time in Epoch format. If it is empty will take it as current time
            label: Baseline StartTime 
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: baselinestarttime
          - defaultValue: "" 
            description: Please enter Canry Start Time  in Epoch format. If it is empty will take it as current time
            label: Canary StartTime
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: canarystarttime
          - defaultValue: "" 
            description: Please enter Gate
            label: Gate Name
            mapping: 'manifest.spec.template.spec.containers[0].env[8].value'
            name: gate
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: verificationgate
            namespace: default
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: lifetime
                        value:
                      - name: minicanaryresult
                        value:
                      - name: canaryresultscore
                        value:
                      - name: log
                        value:
                      - name: metric
                        value:
                      - name: baselinestarttime
                        value:
                      - name: canarystarttime
                        value:
                      - name: gate
                        value:
                      - name: application
                        value: "${execution.application}"
                      - name: service
                        value: "${execution.name}"
                      - name: time
                        value: "${{execution.startTime} .toString()}"
                    image: 'opsmxdev/verificationgate-stage:v1'
                    imagePullPolicy: Always
                    name: verificationgate
                restartPolicy: Never
      - label: VisibilityApproval
        cloudProvider: kubernetes
        credentials: default
        application: spin
        description: Stage for Visibility Approval
        account: default
        type: Visibility Approval
        waitForCompletion: true
        parameters:
          - defaultValue: "" 
            description: Please enter the Gate URL
            label: Gate Url
            mapping: 'manifest.spec.template.spec.containers[0].env[0].value'
            name: gateurl
          - defaultValue: ""
            description: Please enter the JIRA ID
            label: Jira Id 
            mapping: 'manifest.spec.template.spec.containers[0].env[1].value'
            name: jiraid
          - defaultValue: ""
            description: Please enter the Git Repo Name
            label: Git Repo
            mapping: 'manifest.spec.template.spec.containers[0].env[2].value'
            name: gitrepo
          - defaultValue: ""
            description: Please enter the Git Commit Id 
            label: Git Commit Id 
            mapping: 'manifest.spec.template.spec.containers[0].env[3].value'
            name: gitcommitid
          - defaultValue: ""
            description: Please enter the Jenins Job
            label: Jenkins Job Name
            mapping: 'manifest.spec.template.spec.containers[0].env[4].value'
            name: jenkinsjob
          - defaultValue: ""
            description: Please enter the Jenkins Build No 
            label: Jenkins Build No 
            mapping: 'manifest.spec.template.spec.containers[0].env[5].value'
            name: jenkinsbuild
          - defaultValue: ""
            description: Please enter the Autopilot Canary
            label: Autopilot Canary Id
            mapping: 'manifest.spec.template.spec.containers[0].env[6].value'
            name: canaryid
          - defaultValue: ""
            description: Please enter the Sonarqube Prject Key
            label: Sonarqube Project Key
            mapping: 'manifest.spec.template.spec.containers[0].env[7].value'
            name: projectkey
        manifest:
          apiVersion: batch/v1
          kind: Job
          metadata:
            name: visibilityapprove
            namespace: default 
          spec:
            backoffLimit: 0
            template:
              spec:
                containers:
                  - args:
                      -
                    env:
                      - name: gateurl
                        value:
                      - name: jiraid
                        value:
                      - name: gitrepo
                        value:
                      - name: gitcommitid
                        value:
                      - name: jenkinsjob
                        value:
                      - name: jenkinsbuild
                        value:
                      - name: canaryid
                        value:
                      - name: projectkey
                        value: 
                    image: 'opsmxdev/visibility-stage:v1'
                    imagePullPolicy: Always
                    name: visibility-approve
                restartPolicy: Never
