apiVersion: v1
kind: Service
metadata:
  name: spin-deck-np
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: spin
    cluster: spin-deck
  sessionAffinity: None
  type: NodePort
