apiVersion: v1
data:
  run.sh: |
        #!/bin/sh
        #Install SSMTP
        apk add ssmtp
        #Removing default file
        cat /dev/null >/etc/ssmtp/ssmtp.conf
        #Add configuration in ssmtp.conf file
        cat <<EOT>> /etc/ssmtp/ssmtp.conf
        root=$ssmtpemail
        mailhub=smtp.gmail.com:587
        AuthUser=$ssmtpemail
        AuthPass=$emailpassword
        UserTLS=YES
        UseSTARTTLS=YES
        rewriteDomain=gmail.com
        hostname=localhost
        FromLineOverride=YES
        EOT
        #add body to file
        touch body.txt
        cat <<EOT>> body.txt
        $body
        EOT
        export MAILFROM="$ssmtpemail"
        export MAILTO="$email,$ccmail"
        export SUBJECT="$subject"
        export BODY="body.txt"
        (
        echo "From: $MAILFROM"
        echo "To: $MAILTO"
        echo "Subject: $SUBJECT"
        cat $BODY
        ) | /usr/sbin/sendmail $MAILTO
kind: ConfigMap
metadata:
  name: email-config
