{{- if or (eq .Values.installationMode "OES-AP") (eq .Values.installationMode "EASY") -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: oes
    component: datascience
{{ include "oes.standard-labels" . | indent 4 }}
  name: oes-datascience
spec:
  ports:
  - name: datascience
    port: 5005
    protocol: TCP
    targetPort: 5005
  selector:
    app: oes
    component: datascience
  type: ClusterIP
{{- end -}}