{{- if and (.Values.spinnaker.enableMTLS) (.Values.spinnaker.gitopsHalyardInit.enabled) }}
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
{{- end }}
