apiVersion: v1
kind: ServiceAccount
metadata:
  name: isd-info
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: isd-info
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: isd-info
    namespace: mahesh-jmeter #Please update the namespace accordingly

