{{- if .Values.spinnaker.gitopsHalyard.pipelinePromotion.enabled }}
apiVersion: v1
stringData:
  # Git token to access repo where pipeline stuff is stored
  git_secret_token: 160c57e17ca9e246bcefa1f1fb01329e9336f205
kind: Secret
metadata:
  namespace: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.executionNamespace }}
  name: git-token
type: Opaque
{{- end }}
