{{- if .Values.spinnaker.gitopsHalyard.pipelinePromotion.enabled }}
apiVersion: v1
stringData:
  # Git token to access repo where pipeline stuff is stored
  git_secret_token: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.token }}
kind: Secret
metadata:
  namespace: {{ .Values.spinnaker.gitopsHalyard.pipelinePromotion.executionNamespace }}
  name: git-token
type: Opaque
{{- end }}
