{{- if .Values.global.certManager.installed }}
apiVersion: cert-manager.io/v1beta1
kind: Issuer
metadata:
  name: letsencrypt-{{ .Release.Namespace }}-spin
spec:
  acme:
    email: srinivas@opsmx.io
    privateKeySecretRef:
      name: demo-authtls
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
{{- end }}
