apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    strategy.spinnaker.io/max-version-history: '2'
  name: opsmx-restapp
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: opsmx-restapp
  template:
    metadata:
      labels:
        app: opsmx-restapp
        version: '{{ .Values.image.tag }}'
    spec:
      containers:
        - image: >-
            {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: restapp
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
            - containerPort: 9090
              name: prometheus
              protocol: TCP
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
