{{ if .Values.spinnaker.gitopsHalyardInit.enabled }}
apiVersion: v1
data:
  # Repo details to fetch dynamic accounts and halyard configuration
  gitcloneparam: aHR0cHM6Ly9rc3JpbmltYmE6NTM4YzFkYWMyZDA1MWZjMjE2MmJiN2I1OWYwZWJmZmU1NTEyNmZiY0BnaXRodWIuY29tL2tzcmluaW1iYS9naXRvcHMtaGFsZGlyLmdpdA==
  gittoken: NTM4YzFkYWMyZDA1MWZjMjE2MmJiN2I1OWYwZWJmZmU1NTEyNmZiYw==
  gituser: a3NyaW5pbWJh
kind: Secret
metadata:
  name: opsmx-gitops-auth
type: Opaque
{{ end }}
