---
# Source: oes/templates/hooks/cleanup.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: "oes-cleanup"
  labels:
    heritage: "Helm"
    release: "isd"
    chart: "oes-3.12.1"
  annotations:
    "helm.sh/hook": "pre-delete"
    "helm.sh/hook-delete-policy": "before-hook-creation"
spec:
  template:
    metadata:
      labels:
        heritage: "Helm"
        release: "isd"
        chart: "oes-3.12.1"
    spec:
      restartPolicy: OnFailure
      containers:
      - name: oes-cleanup
        image: quay.io/opsmxpublic/ubi8-spin-halyard:opsmx-1.40.0
        command: ["/bin/bash","-c"]
        args: ["kubectl delete ingress --ignore-not-found oes-gate-ingress oes-ui-ingress isd-spinnaker-deck; kubectl delete secret --ignore-not-found ca-secret jwt-secret oes-cacerts oes-control-secret"]
